import Head from "next/head";
import React, { ReactNode } from "react"
import { PageFooter } from "../stories/components/PageFooter/PageFooter"
import { PageHeader } from "../stories/components/PageHeader/PageHeader"
import Script from 'next/script'


export const Layout = (props: { children?: ReactNode }) => {

    const { children } = props;

    const footer = {
        links1: [
            {
                text: "Link 1",
                url: "http://test,com"
            },
            {
                text: "Link 1",
                url: "http://test,com"
            },
            {
                text: "Link 1",
                url: "http://test,com"
            }
            , {
                text: "Link 1",
                url: "http://test,com"
            }
        ],
        links2: [
            {
                text: "Link 1",
                url: "http://test,com"
            },
            {
                text: "Link 1",
                url: "http://test,com"
            },
            {
                text: "Link 1",
                url: "http://test,com"
            }
            , {
                text: "Link 1",
                url: "http://test,com"
            }
        ],
        copyRight: "© 2021 - Environmental Handprint, All Rights Reserved",
        instagram: {
            url: "http://"
        },
        facebook: {
            url: "http://"
        },
        twitter: {
            url: "http://"
        }
    };



    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossOrigin="anonymous" />
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;800&family=Poppins&display=swap" rel="stylesheet" />



            </Head>
            <PageHeader
                title="Environmental Handprint"
                logo="https://media.istockphoto.com/vectors/hand-print-vector-id165761878?k=20&m=165761878&s=612x612&w=0&h=vWMybbPjcI32m3w2Qaiyx1NnMk1COtL1FpaX5_3SJxM="
            />
            {children}

            <PageFooter  {...footer} />


            <Script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossOrigin="anonymous"></Script>
            <Script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossOrigin="anonymous"></Script>
            <Script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossOrigin="anonymous"></Script>

            <Script defer={true} data-search-pseudo-elements async src="https://kit.fontawesome.com/89403bae8e.js" crossOrigin="anonymous"></Script>
            <Script src="/scripts/aos.js"></Script>
        </>
    )
}